### ISSUE TITLE
An alternate C code

### ISSUE THREAD

**Issue by hzhou** [andreaferretti/kmeans#32]
Hi, somehow I hit across your benchmark and got interested. Your C code scores so low which got me interested (doesn't nim compile into C so how can the native C be slower than nim?).

Any way, I wrote my own quick version of bench code and would like you to time on your machine. 

https://github.com/hzhou/kmean. 

You can directly compile the c file 

```
gcc test.c && ./a.out
```

I developed the code in my own meta-layer (MyDef), so if you want a more readable version, you may read test.def directly.

I didn't use any json library nor hash maps, so no dependency and the parsing overhead should be negligible for the benchmark anyway.

Regardless the result, nice work!

**Comment by andreaTP** [comment]
I wrote the C version and, as long as I know, the cause of the low speed could be the use of GLib hashmap. hopefully using a more performing data structure (Judy arrays?) you can significantly increase performances.

**Comment by andreaferretti** [comment]
Hi, I am well aware that one can get more performant implementations by changing the underlying algorithm. The whole point of the exercise is to benchmark different languages performing the same steps. In particular, wherever available I have used a `group-by` operation on collections, which groups collections based on a given attribute, returning a hash map of the groups.

Low level languages do not have this facility, but I have made sure that the implementation follows the scheme above. It would be otherwise easy to makes various other improvements, and I also describe them in the README. But one of the aims of the benchmark is to test the performance of hashmaps. More generally, I intentionally use the naive implementation, because for many other algorithms, similar but not identical to K-means, various optimizations (e.g. avoiding to construct hashmaps along the way) may not be applicable.

So, if you are saying that you are not using hashmaps, I am pretty sure that your implementation will be faster (I also wrote a pretty fast one in Nim which is not in this repo, just to have a lower bound), but it will not be comparable to the other ones here, which is why I am rejecting this
