### ISSUE TITLE
A few languages to try

### ISSUE THREAD

**Issue by jansegre** [andreaferretti/kmeans#5]
I find this experiment interesting. I think these are some interesting languages to try:
- [Julia](http://julialang.org/)
- [Idris](http://www.idris-lang.org/)

**Comment by andreaferretti** [comment]
Yeah, I would be particularly interested in trying Idris. But there is only so much time... Do you have any experience with Idris? I was also having a look at [ATS](http://www.ats-lang.org/), that also introduces depedent types, but uses them in a low-level context, where they can help speed up even C code - think removing array bound checks because the compiler can prove them correct.
